# Generated by Django 4.2.1 on 2023-05-29 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_exercicio', models.TextField()),
                ('dt_inicio', models.DateTimeField(auto_now_add=True)),
                ('dt_fim', models.TextField(blank=True)),
                ('codigo_fonte_problema', models.TextField()),
                ('saida_privada', models.TextField()),
                ('saida_publica', models.TextField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResolucaoExercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcentagem_acerto_publico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentagem_acerto_privado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codigo_fonte_aluno', models.TextField()),
                ('saida_privada_aluno', models.TextField()),
                ('saida_publica_aluno', models.TextField()),
                ('dt_inicio', models.DateTimeField(auto_now_add=True)),
                ('dt_fim', models.TextField(blank=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicio', to='exercicios.exercicios')),
                ('resolvido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolvido_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
